CC ?= gcc
CFLAGS ?= -Wall -Wextra -pedantic -Werror -Wfatal-errors -g -std=gnu99
LDFLAGS ?= -g

FILES = functii3.o main3.o
HEADERS = header3.h
EXEC = EX3

.PHONY: build
build: $(EXEC)

$(EXEC): $(FILES) $(HEADERS)
	$(CC) $(LDFLAGS) -o $(EXEC) $(FILES)

%.o: %.c $(HEADERS)
	$(CC) $(CFLAGS) -c $<

.PHONY: run
run: $(EXEC)
	./$(EXEC)

.PHONY: clean
clean:
	rm $(FILES) $(EXEC)